### ISSUE TITLE
Podspec file needs to be renamed

### ISSUE THREAD

**Issue by aaronash** [Leocardoso94/flutter-countdown#1]
When attempting to use on iOS, I got `No podspec found for...`
I was able to fix the issue in my local project by renaming `.symlinks/plugins/countdown_flutter/ios/countdown.podspec` to `.symlinks/plugins/countdown_flutter/ios/countdown_flutter.podspec` and modifying the `s.name` in that file to be `countdown_flutter`.

I'm guessing it probably broke on this commit: https://github.com/Leocardoso94/flutter-countdown/commit/b599a2701cd1bd6203e83e1c0e18d6c67d555b8b

Let me know if you'd like me to open a PR, but this is probably a quick fix for you.

Thanks for sharing your code!

**Comment by Leocardoso94** [comment]
Thank you for your help! I will fix this!
