### ISSUE TITLE
CountDownFormatted not keeping the format

### ISSUE THREAD

**Issue by dpedrinha** [Leocardoso94/flutter-countdown#3]
If you set the duration to, let's say 5 minutes, the CountDownFormatted shows 00:5:00 (missing a zero).
Also, if I set to one hour it shows 1:00:00 but as soon as there's less than one hour the hours "display" disappear showing only the minutes and seconds like 59:59.
Would be nice to set the format type we want and keep it on the timer.

**Comment by dimiril** [comment]
up

**Comment by Leocardoso94** [comment]
I add a field to CountDownFormatted to set the function that will format the duration. This is a flexible way to set the format
